Repository matter-labs/foundry-zksync, pull requests merged in 2024-11, with the labels that each got.

#690 fix: sanitize input based on solc version
  crates/verify/src/zksync/standard_json.rs
Labels: needs review 👓

#688 feat(compiler:zk): zksolc 1.5.7
  Cargo.lock
  crates/config/src/zksync.rs
Labels: compiler 📟, needs review 👓

#703 fix: add verbosity for verification compilation error
  crates/verify/src/zksync/mod.rs
Labels: needs review 👓

#711 feat(compiler:zk): zksolc linking
  Cargo.lock
  crates/common/src/compile.rs
  crates/forge/bin/cmd/create.rs
  crates/forge/src/multi_runner.rs
  crates/forge/tests/fixtures/zk/Libraries.s.sol
  crates/forge/tests/it/test_helpers.rs
  crates/forge/tests/it/zk/linking.rs
  crates/forge/tests/it/zk/mod.rs
  crates/script/src/build.rs
  crates/zksync/compiler/src/lib.rs
  crates/zksync/compiler/src/zksolc/mod.rs
  testdata/zk/WithLibraries.sol
Labels: compiler 📟, feature ➕, p1 🟠

#608 chore: use alloy zksync
  Cargo.lock
  Cargo.toml
  crates/cast/Cargo.toml
  crates/cast/bin/cmd/send.rs
  crates/cast/src/lib.rs
  crates/cheatcodes/Cargo.toml
  crates/cheatcodes/src/inspector.rs
  crates/cli/Cargo.toml
  crates/cli/src/opts/build/zksync.rs
  crates/cli/src/utils/mod.rs
  crates/common/Cargo.toml
  crates/common/src/provider/mod.rs
  crates/evm/core/src/backend/cow.rs
  crates/evm/core/src/backend/mod.rs
  crates/forge/Cargo.toml
  crates/forge/bin/cmd/create.rs
  crates/script/Cargo.toml
  crates/script/src/broadcast.rs
  crates/zksync/core/Cargo.toml
  crates/zksync/core/src/convert.rs
  crates/zksync/core/src/convert/eip712.rs
  crates/zksync/core/src/lib.rs
  crates/zksync/core/src/utils.rs
  crates/zksync/core/src/vm/runner.rs
  deny.toml
Labels: challenging 🏴‍☠️, p1 🟠, upstream-parity 🟰
